services:

  xsshunterexpress-db:
    image: postgres:latest
    container_name: xsshunter-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 3s
      timeout: 5s
      retries: 5
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/xsshunter/pg_data:/var/lib/postgresql/data/pgdata
    #networks:
    #  - dev

  xsshunterexpress-service:
    image: l4rm4nd/xsshunter:latest
    container_name: xsshunter-service
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/xsshunter/payload-fire-images:/app/payload-fire-images
      #- ~/.config/gcloud/application_default_credentials.json:/gcloud.json
    depends_on:
      xsshunterexpress-db:
        condition: service_healthy
    #networks:
    #  - dev
    #labels:
    #  - traefik.enable=true
    #  - traefik.http.routers.xsshunter.rule=Host(`xss.example.com`)&&PathPrefix(`/`)
    #  - traefik.http.services.xsshunter.loadbalancer.server.port=80
    #  - traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=50000000 # optional, only necessary for enabled file uploads
    #  - traefik.http.middlewares.limit.buffering.maxResponseBodyBytes=50000000 # optional, only necessary for enabled file uploads
    #  - traefik.http.middlewares.limit.buffering.memRequestBodyBytes=50000000 # optional, only necessary for enabled file uploads
    #  - traefik.http.middlewares.limit.buffering.memResponseBodyBytes=50000000 # optional, only necessary for enabled file uploads
    #  - traefik.docker.network=dev
    #  # Part for optional traefik middlewares
    #  - traefik.http.routers.xsshunter.middlewares=local-ipwhitelist@file

  xsshunterexpress-trufflehog:
    image: l4rm4nd/xsshunter:trufflehog
    container_name: xsshunter-trufflehog
    restart: unless-stopped
    expose:
      - 8000
    #networks:
    #  - dev

#networks:
#  dev:
#    external: true
